###import libraries

In [ ]:
# !pip install pandas
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

##Data Gathering or Data loading

In [ ]:
df = pd.read_csv("data.csv")
df

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,11.28,0.90,34,23,1,1,0,45961,48071,250,2,1,1
1,0,9.75,0.23,54,33,1,0,0,26106,25333,205,3,0,0
2,1,10.79,0.91,70,49,0,0,0,9995,29465,67,2,1,0
3,0,11.00,0.43,71,50,0,0,0,10635,7439,242,1,1,0
4,1,14.17,0.83,52,19,0,0,0,15619,49644,397,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,10.14,0.02,69,26,1,0,1,26118,47568,144,3,1,0
1996,1,11.77,1.00,24,45,1,1,1,2572,8063,250,3,1,1
1997,1,16.91,0.22,18,42,0,0,0,14933,24753,250,2,1,1
1998,0,11.15,0.72,46,45,1,0,1,18157,15275,253,3,0,1
1999,1,11.36,0.09,41,45,0,0,0,20729,30463,230,1,1,0

##Data Exploration

In [ ]:
df.head(2)

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,11.28,0.90,34,23,1,1,0,45961,48071,250,2,1,1
1,0,9.75,0.23,54,33,1,0,0,26106,25333,205,3,0,0

In [ ]:
df.tail(2)

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
1998,0,11.15,0.72,46,45,1,0,1,18157,15275,253,3,0,1
1999,1,11.36,0.09,41,45,0,0,0,20729,30463,230,1,1,0

In [ ]:
df.columns

# for cols in df.columns:
#     print(cols)

Index(['Blood_Pressure_Abnormality', 'Level_of_Hemoglobin',
       'Genetic_Pedigree_Coefficient', 'Age', 'BMI', 'Sex', 'Pregnancy',
       'Smoking', 'Physical_activity', 'salt_content_in_the_diet',
       'alcohol_consumption_per_day', 'Level_of_Stress',
       'Chronic_kidney_disease', 'Adrenal_and_thyroid_disorders'],
      dtype='object')

In [ ]:
df.count()

Blood_Pressure_Abnormality       2000
Level_of_Hemoglobin              2000
Genetic_Pedigree_Coefficient     2000
Age                              2000
BMI                              2000
Sex                              2000
Pregnancy                        2000
Smoking                          2000
Physical_activity                2000
salt_content_in_the_diet         2000
alcohol_consumption_per_day      2000
Level_of_Stress                  2000
Chronic_kidney_disease           2000
Adrenal_and_thyroid_disorders    2000
dtype: int64

In [ ]:
df.describe()

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,0.493500,11.710035,0.494595,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,250.886500,2.012500,0.5050,0.443500
std,0.500083,2.186701,0.284945,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,134.676589,0.823822,0.5001,0.496922
min,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,0.000000,10.147500,0.250000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,144.000000,1.000000,0.0000,0.000000
50%,0.000000,11.330000,0.490000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,250.000000,2.000000,1.0000,0.000000
75%,1.000000,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000
max,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Blood_Pressure_Abnormality     2000 non-null   int64
 1   Level_of_Hemoglobin            2000 non-null   float64
 2   Genetic_Pedigree_Coefficient   2000 non-null   float64
 3   Age                            2000 non-null   int64
 4   BMI                            2000 non-null   int64
 5   Sex                            2000 non-null   int64
 6   Pregnancy                      2000 non-null   int64
 7   Smoking                        2000 non-null   int64
 8   Physical_activity              2000 non-null   int64
 9   salt_content_in_the_diet       2000 non-null   int64
 10  alcohol_consumption_per_day    2000 non-null   int64
 11  Level_of_Stress                2000 non-null   int64
 12  Chronic_kidney_disease         2000 non-null   int64
 13  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 218.9 KB

In [ ]:
df.shape
print(f"Number of Rows: {df.shape[0]} and Number of Columns: {df.shape[1]}")

Number of Rows: 2000 and Number of Columns: 14

In [ ]:
df['Age'].unique()

array([34, 54, 70, 71, 52, 23, 43, 48, 72, 40, 35, 31, 75, 18, 65, 61, 36,
       27, 66, 38, 55, 58, 69, 25, 39, 42, 21, 24, 53, 51, 74, 46, 28, 32,
       63, 20, 56, 45, 44, 19, 68, 73, 30, 22, 47, 59, 64, 50, 67, 62, 57,
       60, 49, 33, 29, 37, 26, 41])

In [ ]:
df.nunique()

Blood_Pressure_Abnormality          2
Level_of_Hemoglobin               757
Genetic_Pedigree_Coefficient      101
Age                                58
BMI                                41
Sex                                 2
Pregnancy                           2
Smoking                             2
Physical_activity                1951
salt_content_in_the_diet         1945
alcohol_consumption_per_day       488
Level_of_Stress                     3
Chronic_kidney_disease              2
Adrenal_and_thyroid_disorders       2
dtype: int64

In [ ]:
df.isnull().sum()

Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

## Data pre-processing

Manage null values

In [ ]:
df.columns

Index(['Blood_Pressure_Abnormality', 'Level_of_Hemoglobin',
       'Genetic_Pedigree_Coefficient', 'Age', 'BMI', 'Sex', 'Pregnancy',
       'Smoking', 'Physical_activity', 'salt_content_in_the_diet',
       'alcohol_consumption_per_day', 'Level_of_Stress',
       'Chronic_kidney_disease', 'Adrenal_and_thyroid_disorders'],
      dtype='object')

In [ ]:
 #df.drop('BMI', axis=1, inplace=True)
df = df.drop('BMI', axis=1)

In [ ]:
# df.drop('smoking', axis=1, inplace=True)
df = df.drop('Smoking', axis=1)

In [ ]:
df.isnull().sum()

Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
Sex                              0
Pregnancy                        0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

In [ ]:
def fillnaIntMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['Sex','Age','Level_of_Stress','Pregnancy','Physical_activity','Chronic_kidney_disease']
fillnaIntMode(columns)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Blood_Pressure_Abnormality     2000 non-null   int64
 1   Level_of_Hemoglobin            2000 non-null   float64
 2   Genetic_Pedigree_Coefficient   2000 non-null   float64
 3   Age                            2000 non-null   int64
 4   Sex                            2000 non-null   int64
 5   Pregnancy                      2000 non-null   int64
 6   Physical_activity              2000 non-null   int64
 7   salt_content_in_the_diet       2000 non-null   int64
 8   alcohol_consumption_per_day    2000 non-null   int64
 9   Level_of_Stress                2000 non-null   int64
 10  Chronic_kidney_disease         2000 non-null   int64
 11  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 187.6 KB

##Manage data type

In [ ]:
df['Sex'] = df['Sex'].astype('int64')
# df['price'].astype('int64', inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Blood_Pressure_Abnormality     2000 non-null   int64
 1   Level_of_Hemoglobin            2000 non-null   float64
 2   Genetic_Pedigree_Coefficient   2000 non-null   float64
 3   Age                            2000 non-null   int64
 4   Sex                            2000 non-null   int64
 5   Pregnancy                      2000 non-null   int64
 6   Physical_activity              2000 non-null   int64
 7   salt_content_in_the_diet       2000 non-null   int64
 8   alcohol_consumption_per_day    2000 non-null   int64
 9   Level_of_Stress                2000 non-null   int64
 10  Chronic_kidney_disease         2000 non-null   int64
 11  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 187.6 KB

In [ ]:
 !pip install scikit-learn

 import numpy as np
 from sklearn.preprocessing import LabelEncoder

Requirement already satisfied: scikit-learn in c:\users\abdullah\appdata\local\programs\python\python313\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\abdullah\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.3)
Requirement already satisfied: scipy>=1.8.0 in c:\users\abdullah\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abdullah\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abdullah\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
 data = pd.DataFrame({'Sex':df['Sex'].unique()})
 data_LE = LabelEncoder()
 data_LE.fit(np.ravel(data))    # data_LE.fit(data)
 df['Sex'] = data_LE.transform(df['Sex'])

In [ ]:
def convertObjToInt(cols):
    for i in cols:
        data = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data))    # data_LE.fit(data)
        df[i] = data_LE.transform(df[i])
        
columns = ['Sex', 'Age', 'Pregnancy']
convertObjToInt(columns)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Blood_Pressure_Abnormality     2000 non-null   int64
 1   Level_of_Hemoglobin            2000 non-null   float64
 2   Genetic_Pedigree_Coefficient   2000 non-null   float64
 3   Age                            2000 non-null   int64
 4   Sex                            2000 non-null   int64
 5   Pregnancy                      2000 non-null   int64
 6   Physical_activity              2000 non-null   int64
 7   salt_content_in_the_diet       2000 non-null   int64
 8   alcohol_consumption_per_day    2000 non-null   int64
 9   Level_of_Stress                2000 non-null   int64
 10  Chronic_kidney_disease         2000 non-null   int64
 11  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 187.6 KB

In [ ]:
df.head(2)

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,Sex,Pregnancy,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,11.28,0.90,16,1,1,45961,48071,250,2,1,1
1,0,9.75,0.23,36,1,0,26106,25333,205,3,0,0

In [ ]:
df.to_csv('cleaned_data.csv', index=False, header=True)

In [ ]:
df = pd.read_csv('cleaned_data.csv')
df

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,Sex,Pregnancy,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,11.28,0.90,16,1,1,45961,48071,250,2,1,1
1,0,9.75,0.23,36,1,0,26106,25333,205,3,0,0
2,1,10.79,0.91,52,0,0,9995,29465,67,2,1,0
3,0,11.00,0.43,53,0,0,10635,7439,242,1,1,0
4,1,14.17,0.83,34,0,0,15619,49644,397,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,10.14,0.02,51,1,0,26118,47568,144,3,1,0
1996,1,11.77,1.00,6,1,1,2572,8063,250,3,1,1
1997,1,16.91,0.22,0,0,0,14933,24753,250,2,1,1
1998,0,11.15,0.72,28,1,0,18157,15275,253,3,0,1
1999,1,11.36,0.09,23,0,0,20729,30463,230,1,1,0

In [ ]:
## Train test Spliting

In [ ]:
import pandas as pd
df = pd.read_csv('cleaned_data.csv')
# df.info()
df.columns

Index(['Blood_Pressure_Abnormality', 'Level_of_Hemoglobin',
       'Genetic_Pedigree_Coefficient', 'Age', 'Sex', 'Pregnancy',
       'Physical_activity', 'salt_content_in_the_diet',
       'alcohol_consumption_per_day', 'Level_of_Stress',
       'Chronic_kidney_disease', 'Adrenal_and_thyroid_disorders'],
      dtype='object')

In [ ]:
X = df.drop('Age', axis=1)   # Dependant columns / Input columns
y = df['Age']                # Resultant columns / Output column

In [ ]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.3, shuffle=False) # 80:20, 70:30, 60:40

In [ ]:
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(1400, 11) (1400,)
(600, 11) (600,)

##Applying Classifier

In [ ]:
from sklearn.svm import SVC # Support Vector Classifier

model_svc = SVC()
model_svc.fit(train_X, train_y)

print(model_svc)

SVC()

In [ ]:
model_pred_svc = model_svc.predict(test_X)
model_pred_svc

array([51,  7, 51, 51, 50, 40, 51,  7, 51,  7, 50, 40, 51, 40,  3, 50, 40,
       50, 50, 50, 51, 31, 40, 40, 31, 40, 50, 51, 51, 40,  7, 40, 50,  7,
       51, 51, 51, 31, 46, 50,  7, 31,  7, 40, 31,  7,  7, 51, 51, 51, 40,
        7, 51, 40,  7, 40, 40, 50, 50, 51,  7, 50, 40, 46,  7,  7,  7, 50,
        3,  7, 51,  7, 51, 40,  7,  7, 51, 51, 31, 51, 40, 50, 50, 50,  7,
       50,  7, 31, 50,  3,  7,  7,  7,  7, 51, 31, 40,  7, 31, 51, 51, 40,
        7,  7, 50,  7,  7, 50,  7, 40,  7, 40, 51, 31, 40, 51, 31, 51, 50,
       51, 51, 51, 50, 50, 50, 40,  7, 51, 50, 50, 50,  7, 31,  7, 40,  7,
       50, 51, 31,  7, 50, 31,  7, 50,  7, 50, 50, 40, 51, 31,  7, 51,  7,
       50, 51,  7, 50,  7, 50,  7,  7, 31, 40,  7,  7, 51, 50,  7,  7, 50,
        7, 40,  7,  7, 40,  7,  7, 31, 51,  7, 50, 50, 40, 51, 31, 51, 50,
       40, 50, 31,  7, 31,  7,  7, 31,  7,  7, 40,  7, 50,  7, 31, 50,  7,
       51,  7, 51,  7, 50, 51, 50,  7,  7, 40, 51, 40, 50, 50,  7, 40, 50,
        7, 50, 51,  7,  7, 40, 31, 40, 40,  7,  7, 51, 40,  7, 51,  7, 51,
       51, 40,  7, 31, 50,  7, 50, 51,  7, 40, 40,  7, 31, 50,  7, 40,  7,
       51, 50, 51, 31, 51, 50, 40,  7, 40, 31,  7, 51, 50, 51, 51, 50, 51,
        7,  7, 51, 50,  7,  7, 40,  7, 40, 51, 50, 31, 50, 51,  7, 31, 50,
       31, 31, 50, 51,  7,  7, 51, 40, 51,  7, 31, 50, 50,  7, 50, 40, 40,
        7,  7,  7, 40, 51, 50, 40, 51, 31,  7,  7, 50,  7, 50,  7, 51,  7,
       50, 50, 40, 50, 50,  7,  7, 50, 50,  7, 51,  7, 50,  7, 40,  7,  7,
       50, 31, 40, 31, 50, 40, 51,  7, 50,  7, 51, 46, 31,  7, 51, 51, 50,
        7, 50,  7,  7, 31, 31, 51, 51, 40,  7,  7, 40, 31,  7, 50, 50, 50,
       50, 51,  7, 51, 40, 50,  7, 51, 40, 50,  7, 31, 50, 51, 50, 40,  7,
       31, 50, 50, 51, 40, 50, 51, 51, 40, 40,  7, 31, 40, 50, 40, 51, 51,
       51, 51,  7, 51,  7, 51,  7,  7, 31, 51,  7,  7, 40,  7, 50, 40,  7,
        7, 50,  7, 31, 31,  7,  7, 51,  7,  7, 40,  7, 31, 40,  7,  7,  7,
       51, 51, 51, 50, 40,  3, 31, 40,  7, 51,  7,  7, 51, 31, 40,  7,  7,
       51, 50,  7, 51,  7, 51, 50, 40, 40,  7, 51, 51, 51,  7, 51,  7,  7,
       40,  7, 50,  7, 40, 40,  7,  7, 50, 50, 50, 40,  7, 50, 51,  7, 40,
       31, 50,  7, 31,  7,  7, 40,  7, 51, 51, 50, 40, 50, 40, 51,  7, 40,
       31,  7, 40, 31, 50, 50, 40, 51, 40,  7,  7, 31,  7, 50,  7,  7, 51,
        7, 50, 50, 40, 50,  7,  7, 40, 40,  7, 50, 51, 50, 51, 31,  7, 31,
        7,  7,  7, 40, 50, 40, 31, 51,  7,  7,  7,  7,  7, 40,  7,  7, 51,
       40, 40, 40,  7,  7,  7, 50,  7, 50, 50, 50,  3,  7, 50, 51, 40, 31,
       50, 51, 50, 40, 51, 50,  7,  7, 51, 50, 31,  3, 51, 51, 51, 50, 50,
        7, 40,  7, 40,  7])

In [ ]:
from sklearn.metrics import accuracy_score
model_acc_svc = accuracy_score(test_y, model_pred_svc)
print(round(model_acc_svc,3)*100, "%")

2.0 %

In [ ]:
import pickle
pickle.dump(model_svc, open('model_svc.pkl', 'wb'))   # Model Saving

In [ ]:
import pickle
model_svc = pickle.load(open('model_svc.pkl', 'rb'))  # Model Loading